const identify = {
  publicKeyHash: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
  accounts: [
    {
      delegate_setable: true,
      script: null,
      operations: {},
      account_id: 'KT1HE1JLUZwsVYaCTBaGUnk652TfvWWeBsCu',
      block_id: 'BLmKgSbbdFvzK7msj2u3KECuzhoCzT6qE1BeihVwdZbGEArkrU4',
      manager: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      order: 1,
      activeTab: 'general.nouns.transactions',
      block_level: 192282,
      status: 'Ready',
      transactions: [],
      publicKey: 'edpku3kouMjp8Ubnd2WV99EB5AVvUZGickTnn4XDd3XL3grvvhwkB6',
      delegate_value: 'tz3gN8NTLNLJg5KRsUU47NHNVHbdhcFXjjaB',
      spendable: true,
      privateKey:
        'edskRwXtbk7xKJm49JSeQDMFyDbPJS8Y5uHHtr9pZEpj3Wts5dCVkSVfMaucFa3gxVnGE5b4z4UaQSPebGMdFvcNeZYQ1mP58j',
      counter: 2,
      balance: 899997259
    }
  ],
  operations: {},
  order: 1,
  activeTab: 'general.nouns.transactions',
  status: 'Ready',
  transactions: [
    {
      block_hash: 'BKqrzXSbPf1ibBWzdxdT5LvZuKQjRVDKf8FfEdvQ3UcSTgVmK1u',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'oou3oxNVbHtnvBHAJ4noBRD5nR9QcRru8dMweAHi7A23npd7heg',
      fee: 300000,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      nonce: null,
      secret: null,
      block_level: 189957,
      status: 'Ready',
      operation_id: 1421450,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550772858000,
      storage_limit: 300,
      amount: 1000000,
      spendable: null,
      delegatable: null,
      source: 'tz1KjhLYva5iYAyGmw8bPZFrErnhw9H21Lg6',
      counter: 16338,
      balance: null
    },
    {
      block_hash: 'BL2mjf87HLCkCFRXMgoXtQrSG2fwrMC9SBCQFnKCKyjFgwNDNfY',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'ooTodj4LhbksRC4k66Cy9oJgBp5W4nADWG4cXJvBQuzfVMhqPcj',
      fee: 1420,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      nonce: null,
      secret: null,
      block_level: 189708,
      status: 'Ready',
      operation_id: 1422713,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550764348000,
      storage_limit: 300,
      amount: 50000000,
      spendable: null,
      delegatable: null,
      source: 'tz1bYDK6m4RhCjMmCUTfUeuZ1WaiZZcHQZHN',
      counter: 27189,
      balance: null
    },
    {
      block_hash: 'BM1t1frvUs7xoV911gDS7bMCczJDgGBZNip3aDB7VahkUjjh96q',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'oot4LAohfCYd1wa6Zz9HaiNUb5MbP7iiULDjG1V9z9YojBXLgi2',
      fee: 2720,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      nonce: null,
      secret: null,
      block_level: 187496,
      status: 'Ready',
      operation_id: 1400681,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550684868000,
      storage_limit: 300,
      amount: 50000000,
      spendable: null,
      delegatable: null,
      source: 'tz1bYDK6m4RhCjMmCUTfUeuZ1WaiZZcHQZHN',
      counter: 27188,
      balance: null
    },
    {
      block_hash: 'BKvGRSkbPYPP1K4HwxWFQQWLZv484pbwPG3D7PA7P8j327NV8fB',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'ootiQXFUJGiqkbFKUz7tcDRNpUQ1EVJbX1h7MwrJCHYCyrUJoXW',
      fee: 1452,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1bYDK6m4RhCjMmCUTfUeuZ1WaiZZcHQZHN',
      nonce: null,
      secret: null,
      block_level: 192327,
      status: 'Ready',
      operation_id: 1444011,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550852238000,
      storage_limit: 300,
      amount: 100000000,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27048,
      balance: null
    },
    {
      block_hash: 'BLsUwFSrnTWCkaEfAHTBZhBWfbsPzvaaS5fvo7DC5A4c7goLfbD',
      consumed_gas: 10000,
      level: null,
      delegate: 'tz3gN8NTLNLJg5KRsUU47NHNVHbdhcFXjjaB',
      operation_group_hash:
        'opAXKypVamHJuCuVPxxPU2f4s8j6neGHqk15SfWHWMgJsVatPnt',
      fee: 1441,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: null,
      nonce: null,
      secret: null,
      block_level: 192279,
      status: 'Ready',
      operation_id: 1443637,
      manager_pubkey: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      kind: 'origination',
      slots: null,
      gas_limit: 10160,
      timestamp: 1550850198000,
      storage_limit: 277,
      amount: null,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27047,
      balance: 1000000000
    },
    {
      block_hash: 'BMQ7SAPWrNErueM1svxGW6WwGcQtqmZRkSNKNR7nZqziMSjvazw',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'op3a5Ztu6yPUZYP4HVaSFXwLs3vNQF6BD7y9You1svrAzxp9Gfu',
      fee: 1441,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1bYDK6m4RhCjMmCUTfUeuZ1WaiZZcHQZHN',
      nonce: null,
      secret: null,
      block_level: 192269,
      status: 'Ready',
      operation_id: 1443554,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550849818000,
      storage_limit: 300,
      amount: 100000000,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27046,
      balance: null
    },
    {
      block_hash: 'BLrNVs7trfer3JMH85UrRnLpAyZBtXx9ajwtg7ZuZDMLZJ3UGfG',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'opGVHfWGkRKEw5uUw15XpKMsdAZy61MhfdQxa7nMBmXghUpRZdW',
      fee: 1420,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1KjhLYva5iYAyGmw8bPZFrErnhw9H21Lg6',
      nonce: null,
      secret: null,
      block_level: 189953,
      status: 'Ready',
      operation_id: 1419190,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550772738000,
      storage_limit: 300,
      amount: 1000000000,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27045,
      balance: null
    },
    {
      block_hash: 'BKiwxCuX6ushgAChvubEFEsDzCvc2UQnFFHH16MH8CobYmP2xgL',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'opB98UrLfNJV5Nur3BWeFvge5nAn527tsYczu6LJ7HBqoVcEkhr',
      fee: 1420,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1aNjXKVKpriMTzwu8hVqrinkzKNgvc4jQP',
      nonce: null,
      secret: null,
      block_level: 188177,
      status: 'Ready',
      operation_id: 1407665,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550711898000,
      storage_limit: 300,
      amount: 2000000000,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27044,
      balance: null
    },
    {
      block_hash: 'BLKN4n5xEgghA1oUtLmZ8yJgfEaZB2Yfx4fLb5EuaAQSCU7JBTM',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'ooiPYabnhzfGqaZZaHZ49U8pksaSgBKjASRUDAEkN7VzYNfm54J',
      fee: 1420,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1bYDK6m4RhCjMmCUTfUeuZ1WaiZZcHQZHN',
      nonce: null,
      secret: null,
      block_level: 187491,
      status: 'Ready',
      operation_id: 1397231,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550684718000,
      storage_limit: 300,
      amount: 1000000000,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27043,
      balance: null
    },
    {
      block_hash: 'BLwu2UHSkWzhDSwARTMY3PpbjDgrc27Vhhb5m7i5wbNzahCKMjT',
      consumed_gas: 10100,
      level: null,
      delegate: null,
      operation_group_hash:
        'ooWeLLZddSxiu9uoxVx2rRsBo8SPV4yMDWAA7cdXFXRBTCC8uJH',
      fee: 2720,
      public_key: null,
      parameters: null,
      script: null,
      pkh: null,
      destination: 'tz1QK8CSZbudvRshPrFpXnWWN9xig629mnAo',
      nonce: null,
      secret: null,
      block_level: 187412,
      status: 'Ready',
      operation_id: 1400034,
      manager_pubkey: null,
      kind: 'transaction',
      slots: null,
      gas_limit: 10300,
      timestamp: 1550681788000,
      storage_limit: 300,
      amount: 5000000000,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27042,
      balance: null
    },
    {
      block_hash: 'BLwu2UHSkWzhDSwARTMY3PpbjDgrc27Vhhb5m7i5wbNzahCKMjT',
      consumed_gas: 10000,
      level: null,
      delegate: null,
      operation_group_hash:
        'ooWeLLZddSxiu9uoxVx2rRsBo8SPV4yMDWAA7cdXFXRBTCC8uJH',
      fee: 0,
      public_key: 'edpku3kouMjp8Ubnd2WV99EB5AVvUZGickTnn4XDd3XL3grvvhwkB6',
      parameters: null,
      script: null,
      pkh: null,
      destination: null,
      nonce: null,
      secret: null,
      block_level: 187412,
      status: 'Ready',
      operation_id: 1400033,
      manager_pubkey: null,
      kind: 'reveal',
      slots: null,
      gas_limit: 10000,
      timestamp: 1550681788000,
      storage_limit: 0,
      amount: null,
      spendable: null,
      delegatable: null,
      source: 'tz1WAUJCqjTKsJ9D729t1DqXnPdATrYFCmwT',
      counter: 27041,
      balance: null
    }
  ],
  publicKey: 'edpku3kouMjp8Ubnd2WV99EB5AVvUZGickTnn4XDd3XL3grvvhwkB6',
  storeType: 'Fundraiser',
  privateKey:
    'edskRwXtbk7xKJm49JSeQDMFyDbPJS8Y5uHHtr9pZEpj3Wts5dCVkSVfMaucFa3gxVnGE5b4z4UaQSPebGMdFvcNeZYQ1mP58j',
  balance: 59548946255
};

export default identify;
