# Config adapted from:
# https://www.electron.build/multi-platform-build#sample-travisyml-to-build-electron-app-for-macos-linux-and-windows
sudo: true
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - 8
    - os: linux
      services:
        - docker
        - xvfb
      language: node_js
      node_js:
        - 8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libudev-dev
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
            - xorriso
            - rpm

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

install:
  - yarn
  # On Linux, initialize "virtual display". See before_script
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      /sbin/start-stop-daemon \
      --start \
      --quiet \
      --pidfile /tmp/custom_xvfb_99.pid \
      --make-pidfile \
      --background \
      --exec /usr/bin/Xvfb \
      -- :99 -ac -screen 0 1280x1024x16
    else
      :
    fi

script:
  - node --version
  #- yarn lint
  - yarn package
