export const SET_WALLET = 'SET_WALLET';
export const SET_WALLET_FILENAME = 'SET_WALLET_FILENAME';
export const SET_WALLET_LOCATION = 'SET_WALLET_LOCATION';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_IDENTITIES = 'SET_IDENTITIES';
export const LOGOUT = 'LOGOUT';